### ISSUE TITLE
mod_reader will not install due to depency qtype_ordering is not available

### ISSUE THREAD

**Issue by drachels** [gbateson/moodle-mod_reader#1]
I tried to install mod_reader as part of qa testing for Moodle 2.7, as it was the only activity listed as being compatible with 2.7. It fails to install due to dependency on qtype_ordering which is not available on moodle.org

**Comment by gbateson** [comment]
You can get the qtype_ordering plugin from here:
https://github.com/gbateson/moodle-qtype_ordering

**Comment by gbateson** [comment]
The ordering question type is now available on Moodle.org, so I am closing this issue on github.com. Feel free to reopen it if this issue is still a problem for you. best regards, Gordon
